#!/usr/bin/env bash
set -e

FILES=("${@}")
if [[ "${#FILES[@]}" = "0" ]]; then
  FILES+=($(find test/integration -name "*.js"))
fi

OPTIONS=()
if [[ "${CIRCLE_TEST_REPORTS}" != "" ]]; then
  OPTIONS+=(
    --reporter mocha-circleci-reporter
    --reporter-options mochaFile="${CIRCLE_TEST_REPORTS}"/test:integration.xml
  )
fi

./node_modules/.bin/mocha \
  "${OPTIONS[@]}" \
  --require babel-register \
  --require ./test/env/integration \
  "${FILES[@]}"
